import './globals.css'; // Importa los estilos globales aquí

export const metadata = {
  title: 'Mi Aplicación',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>{children}</body>
    </html>
  );
}